### ISSUE TITLE
errors due to uncaught Promise failures aren't showing up in activation record

### ISSUE THREAD

**Issue by starpit** [apache/openwhisk#1930]
for this function, OpenWhisk returns a poor response. this lack of catching uncaught promise failures means that i have to insert catches everywhere in my code:

```
function main(params) {
    return new Promise(resolve => resolve(params.zoo.bar))
}
```

```
% wsk action create uncaught-promise uncaught-promise.js
% wsk action invoke uncaught-promise -br
{
    "error": {}
}
```

in contrast:

```
function main(params) {
    return params.zoo.bar
}
```

```
% wsk action create uncaught-regular uncaught-regular.js
% wsk action invoke uncaught-regular -br
{
    "error": "An error has occurred: TypeError: Cannot read property 'bar' of undefined"
}
```

**Comment by bjustin-ibm** [comment]
This is very curious. Looking at the code, it seems as though your rejection is caught, but it doesn't contain anything to display as an error https://github.com/openwhisk/openwhisk/blob/master/core/nodejsActionBase/runner.js#L108

**Comment by starpit** [comment]
i agree this is weird. i don't have an explanation, yet, as to why my test case fails in whisk. the runner code *does* seem to do the right thing, here. nonetheless, whisk produces suboptimal output!

**Comment by bjustin-ibm** [comment]
Stranger still
```javascript
function main(params) {
	return new Promise(function(resolve, reject) {
		var result;

		try {
			result = params.cannot.be.found;
		} catch(e) {
			console.log("I caught e: " + e);
			reject(e);
		}

		resolve(result);
	});
}
```

This expanded version still produces the `{ "error": {} }` result but the logs clearly show that `e` is the exception you would expect to get. I think we can go back to blaming something going wrong with the Node runtime's handling of this situation.

**Comment by starpit** [comment]
the whisk bits all seems to mock correctly on my laptop with node 6.9.2;

zip actions also fail in this fashion.

**Comment by rabbah** [comment]
```
> wsk action invoke t -r
{
    "error": {
        "message": "Cannot read property 'bar' of undefined",
        "name": "TypeError",
        "stack": "TypeError: Cannot read property 'bar' of undefined\n    at resolve (eval at initializeActionHandler (/nodejsAction/runner.js:57:23), <anonymous>:2:54)\n    at new Promise (<anonymous>)\n    at NodeActionRunner.main [as userScriptMain] (eval at initializeActionHandler (/nodejsAction/runner.js:57:23), <anonymous>:2:12)\n    at Promise (/nodejsAction/runner.js:73:35)\n    at new Promise (<anonymous>)\n    at NodeActionRunner.run (/nodejsAction/runner.js:71:16)\n    at doRun (/nodejsAction/src/service.js:198:14)\n    at runCode (/nodejsAction/src/service.js:143:20)\n    at /nodejsAction/platform/platform.js:125:17\n    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)"
    }
}
```
