### ISSUE TITLE
Controller does not start if invoker health action is corrupted 

### ISSUE THREAD

**Issue by dubee** [apache/openwhisk#2940]
I've noticed that when the database entry for invokerHealthTestAction# is malformed in someway that the controller will fail to start up properly.

```
[2017-11-07T19:04:44.406Z] [INFO] Slf4jLogger started
[2017-11-07T19:04:44.622Z] [INFO] Starting remoting
[2017-11-07T19:04:44.852Z] [INFO] Remoting started; listening on addresses :[akka.tcp://controller-actor-system@192.168.99.100:8000]
[2017-11-07T19:04:44.855Z] [INFO] Remoting now listens on addresses: [akka.tcp://controller-actor-system@192.168.99.100:8000]
[2017-11-07T19:04:44.877Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@192.168.99.100:8000] - Starting up...
[2017-11-07T19:04:44.967Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@192.168.99.100:8000] - Registered cluster JMX MBean [akka:type=Cluster]
[2017-11-07T19:04:44.973Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@192.168.99.100:8000] - Started up successfully
[2017-11-07T19:04:45.021Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@192.168.99.100:8000] - No seed-nodes configured, manual cluster join required
[2017-11-07T19:04:45.874Z] [INFO] [??] [Config] environment set value for db.whisk.actions
[2017-11-07T19:04:45.875Z] [INFO] [??] [Config] environment set value for limits.actions.sequence.maxLength
[2017-11-07T19:04:45.877Z] [INFO] [??] [Config] environment set value for limits.triggers.fires.perMinute
[2017-11-07T19:04:45.878Z] [INFO] [??] [Config] environment set value for db.protocol
[2017-11-07T19:04:45.880Z] [INFO] [??] [Config] environment set value for akka.cluster.seed.nodes
[2017-11-07T19:04:45.880Z] [INFO] [??] [Config] environment set value for loadbalancer.invokerBusyThreshold
[2017-11-07T19:04:45.881Z] [INFO] [??] [Config] environment set value for controller.instances
[2017-11-07T19:04:45.882Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.concurrent
[2017-11-07T19:04:45.883Z] [INFO] [??] [Config] environment set value for whisk.version.date
[2017-11-07T19:04:45.884Z] [INFO] [??] [Config] environment set value for controller.localBookkeeping
[2017-11-07T19:04:45.886Z] [INFO] [??] [Config] environment set value for db.port
[2017-11-07T19:04:45.888Z] [INFO] [??] [Config] environment set value for whisk.version.buildno
[2017-11-07T19:04:45.888Z] [INFO] [??] [Config] environment set value for db.username
[2017-11-07T19:04:45.889Z] [INFO] [??] [Config] environment set value for db.whisk.activations
[2017-11-07T19:04:45.894Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.perMinute
[2017-11-07T19:04:45.894Z] [INFO] [??] [Config] environment set value for db.whisk.auths
[2017-11-07T19:04:45.896Z] [INFO] [??] [Config] environment set value for runtimes.manifest
[2017-11-07T19:04:45.898Z] [INFO] [??] [Config] environment set value for kafka.host.port
[2017-11-07T19:04:45.899Z] [INFO] [??] [Config] environment set value for limits.actions.invokes.concurrentInSystem
[2017-11-07T19:04:45.900Z] [INFO] [??] [Config] environment set value for controller.blackboxFraction
[2017-11-07T19:04:45.902Z] [INFO] [??] [Config] environment set value for db.host
[2017-11-07T19:04:45.903Z] [INFO] [??] [Config] environment set value for port
[2017-11-07T19:04:45.904Z] [INFO] [??] [Config] environment set value for db.provider
[2017-11-07T19:04:45.906Z] [INFO] [??] [Config] environment set value for db.password
[2017-11-07T19:04:45.907Z] [INFO] [??] [Config] environment set value for kafka.host
[2017-11-07T19:04:46.298Z] [INFO] [#sid_130] [Controller] starting controller instance 0 [marker:controller_startup0_count:417]
[2017-11-07T19:04:47.723Z] [INFO] [#sid_120] [LoadBalancerService] blackboxFraction = 0.1
[2017-11-07T19:04:47.758Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@192.168.99.100:8000] - Node [akka.tcp://controller-actor-system@192.168.99.100:8000] is JOINING, roles []
[2017-11-07T19:04:47.762Z] [INFO] [#sid_110] [MessageFeed] handler capacity = 128, pipeline fill at = 128, pipeline depth = 256
[2017-11-07T19:04:47.800Z] [INFO] Cluster Node [akka.tcp://controller-actor-system@192.168.99.100:8000] - Leader is moving node [akka.tcp://controller-actor-system@192.168.99.100:8000] to [Up]
[2017-11-07T19:04:47.958Z] [INFO] [??] [SharedDataService] Member is Up: akka.tcp://controller-actor-system@192.168.99.100:8000
[2017-11-07T19:04:47.959Z] [INFO] [??] [SharedDataService] Member is Up: akka.tcp://controller-actor-system@192.168.99.100:8000
[2017-11-07T19:04:48.353Z] [INFO] [#sid_120] [WhiskAction] [GET] serving from datastore: CacheKey(whisk.system/invokerHealthTestAction0) [marker:database_cacheMiss_count:2472]
[2017-11-07T19:04:48.356Z] [INFO] [#sid_120] [CouchDbRestStore] [GET] 'dockermachine_whisks' finding document: 'id: whisk.system/invokerHealthTestAction0' [marker:database_getDocument_start:2472]
[2017-11-07T19:04:48.835Z] [INFO] [#sid_120] [CouchDbRestStore] [GET] 'dockermachine_whisks' completed: found document 'id: whisk.system/invokerHealthTestAction0' [marker:database_getDocument_finish:2963:491]
[2017-11-07T19:04:48.912Z] [INFO] [#sid_120] [WhiskAction] invalidating CacheKey(whisk.system/invokerHealthTestAction0)
[2017-11-07T19:04:48.937Z] [ERROR] [#sid_120] [LoadBalancerService] error creating test action for invoker health: whisk.core.database.DocumentTypeMismatchException: document type class whisk.core.entity.WhiskTrigger did not match expected type class whisk.core.entity.WhiskAction.
Exception in thread "main" whisk.core.database.DocumentTypeMismatchException: document type class whisk.core.entity.WhiskTrigger did not match expected type class whisk.core.entity.WhiskAction.
	at whisk.core.database.CouchDbRestStore$$anonfun$13.apply(CouchDbRestStore.scala:200)
	at whisk.core.database.CouchDbRestStore$$anonfun$13.apply(CouchDbRestStore.scala:194)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by rabbah** [comment]
Working as expected?
