### ISSUE TITLE
Errors in openwhisk-controller pod

### ISSUE THREAD

**Issue by beth2016** [apache/openwhisk#4946]
I am seeing the following error message in the controller pod during helm install.    Please advice.

[2020-08-20T17:13:58.455Z] [ERROR] [#tid_33d54c1042cacb4de419e1e086e26735] [CouchDbRestStore] Unexpected http response code: 404 Not Found (details: {"error":"not_found","reason":"missing"}
) [marker:database_queryView_error:12:8]
[2020-08-20T17:13:58.455Z] [INFO] [#tid_33d54c1042cacb4de419e1e086e26735] [Identity] invalidating CacheKey(789c46b1-71f6-4ed5-8c54-816aa4f8c502)
[2020-08-20T17:13:58.456Z] [ERROR] [#tid_33d54c1042cacb4de419e1e086e26735] [BasicAuthenticationDirective] authentication error: org.apache.openwhisk.core.database.QueryException: Unexpected http response code: 404 Not Found (details: {"error":"not_found","reason":"missing"}
)
[2020-08-20T17:13:58.456Z] [ERROR] Error during processing of request: 'Unexpected http response code: 404 Not Found (details: {"error":"not_found","reason":"missing"}
)'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
org.apache.openwhisk.core.database.QueryException: Unexpected http response code: 404 Not Found (details: {"error":"not_found","reason":"missing"}
)
        at org.apache.openwhisk.core.database.CouchDbRestStore.$anonfun$query$5(CouchDbRestStore.scala:313)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by beth2016** [comment]
i found the problem.
