### ISSUE TITLE
standalone docker image fails due to typo in volume mount

### ISSUE THREAD

**Issue by dgrove-oss** [apache/openwhisk#5016]
Following instructions in standalone README to launch standalone docker image.

```
Daves-MacBook-Pro:openwhisk dgrove$ ./core/standalone/start.sh 
...
ok: whisk auth set. Run 'wsk property get --auth' to see the new value.
ok: whisk API host set to http://openwhisk:3233
server still not ready - retrying
server still not ready - retrying
....
```

Got the logs...
```
Daves-MacBook-Pro:openwhisk dgrove$ docker logs openwhisk
+ java -Dwhisk.standalone.host.name=openwhisk -Dwhisk.standalone.host.internal=172.17.0.3 -Dwhisk.standalone.host.external=localhost -jar openwhisk-standalone.jar --no-browser

        ____      ___                   _    _ _     _     _
       /\   \    / _ \ _ __   ___ _ __ | |  | | |__ (_)___| | __
  /\  /__\   \  | | | | '_ \ / _ \ '_ \| |  | | '_ \| / __| |/ /
 /  \____ \  /  | |_| | |_) |  __/ | | | |/\| | | | | \__ \   <
 \   \  /  \/    \___/| .__/ \___|_| |_|__/\__|_| |_|_|___/_|\_\
  \___\/ tm           |_|
    
Git Commit: ddb2662, Build Date: 2020-10-27T14:26:23+0000
================================================================================
Running pre flight checks ...

Local Host Name: openwhisk
Local Internal Name: 172.17.0.3

[  OK   ] 'docker' cli found. (Docker version 18.06.3-ce, build d7080c1)
[  OK   ] 'docker' version 18.6.3 is newer than minimum supported 18.3.0
[FAILURE] 'docker' not found to be running. Failed to run 'docker info'
[  OK   ] 'wsk' cli found. (2019-09-23T17:46:38.323+0000)
[  OK   ] 'wsk' configured for namespace [guest].
[  OK   ] 'wsk' configured to connect to http://openwhisk:3233.
[  OK   ] Server port [3233] is free

================================================================================
[2020-10-29T00:14:02.558Z] [INFO] Starting OpenWhisk standalone on port 3233
[2020-10-29T00:14:03.024Z] [INFO] Slf4jLogger started
[2020-10-29T00:14:03.325Z] [INFO] Using [/root/.openwhisk/standalone/server-3233] as data directory
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-10-29T00:14:03.757Z] [ERROR] [#tid_sid_unknown] [StandaloneDockerClient] Failed to determine docker client version: class org.apache.openwhisk.core.containerpool.docker.ProcessUnsuccessfulException - info: command was unsuccessful, code: 1 (unsuccessful), stdout: 18.06.3-ce, stderr: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:86)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.apache.openwhisk.core.containerpool.docker.ProcessUnsuccessfulException: info: command was unsuccessful, code: 1 (unsuccessful), stdout: 18.06.3-ce, stderr: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
	at org.apache.openwhisk.core.containerpool.docker.ProcessRunner.$anonfun$executeProcess$6(ProcessRunner.scala:65)
	at org.apache.openwhisk.core.containerpool.docker.ProcessRunner$$Lambda$671/00000000909E56D0.apply(Unknown Source)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.Future$$Lambda$672/0000000090E32F90.apply(Unknown Source)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.Promise$$Lambda$674/0000000090E335D0.apply(Unknown Source)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$Lambda$673/00000000FC0043B0.apply$mcV$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by starpit** [comment]
i might be seeing this, too, in travis with ubuntu bionic.

**Comment by starpit** [comment]
also, related (but probably not closely enough to be tracked by this issue alone): the instructions for acquiring the credentials:

> docker logs openwhisk | grep 'wsk property'

does not work without some very careful massaging... at least in ubuntu 20's docker, since the docker logs have ANSI control characters in them.

**Comment by style95** [comment]
@dgrove-oss 
As logs stand for, it failed to run `docker info`, are you able to run it manually?
And could you share the output of it?

**Comment by style95** [comment]
It is strange that we are using the same docker version even the build number.

```
imac27:standalone style95$ docker logs openwhisk
+ java -Dwhisk.standalone.host.name=openwhisk -Dwhisk.standalone.host.internal=172.17.0.2 -Dwhisk.standalone.host.external=localhost -jar openwhisk-standalone.jar --no-browser

        ____      ___                   _    _ _     _     _
       /\   \    / _ \ _ __   ___ _ __ | |  | | |__ (_)___| | __
  /\  /__\   \  | | | | '_ \ / _ \ '_ \| |  | | '_ \| / __| |/ /
 /  \____ \  /  | |_| | |_) |  __/ | | | |/\| | | | | \__ \   <
 \   \  /  \/    \___/| .__/ \___|_| |_|__/\__|_| |_|_|___/_|\_\
  \___\/ tm           |_|

Git Commit: 9a1a308, Build Date: 2020-10-26T23:21:28+0900
================================================================================
Running pre flight checks ...

Local Host Name: openwhisk
Local Internal Name: 172.17.0.2

[  OK   ] 'docker' cli found. (Docker version 18.06.3-ce, build d7080c1)
[  OK   ] 'docker' version 18.6.3 is newer than minimum supported 18.3.0
[  OK   ] 'docker' is running.
[  OK   ] 'wsk' cli found. (2019-09-23T17:46:38.323+0000)
[  OK   ] 'wsk' configured for namespace [guest].
[  OK   ] 'wsk' configured to connect to http://openwhisk:3233.
[  OK   ] Server port [3233] is free

================================================================================
[2020-10-30T14:25:40.045Z] [INFO] Starting OpenWhisk standalone on port 3233
[2020-10-30T14:25:40.405Z] [INFO] Slf4jLogger started
[2020-10-30T14:25:40.603Z] [INFO] Using [/root/.openwhisk/standalone/server-3233] as data directory
[2020-10-30T14:25:40.937Z] [INFO] [#tid_sid_unknown] [StandaloneDockerClient] Detected docker client version 18.06.3-ce
[2020-10-30T14:25:41.002Z] [INFO] [#tid_sid_standalone] [StandaloneDockerClient] running /usr/bin/docker ps --quiet --no-trunc --all --filter name=whisk- (timeout: 1 minute) [marker:invoker_docker.ps_start:4]
[2020-10-30T14:25:41.154Z] [INFO] [#tid_sid_standalone] [StandaloneDockerClient]  [marker:invoker_docker.ps_finish:157:41]
[2020-10-30T14:25:41.165Z] [INFO] [#tid_sid_standalone] [StandaloneDockerSupport] removing 0 containers launched for Standalone server support.
================================================================================
Launched service details

[ 3233  ] http://openwhisk:3233 (Controller)
[ 3232  ] http://openwhisk:3232/playground (Playground)

Local working directory - /root/.openwhisk/standalone/server-3233
================================================================================
```

**Comment by dgrove-oss** [comment]
My host docker is Docker Desktop (MacOS) 2.4.0.0.  I suspect the 18.0.x client in the docker image is having problems using the docker.sock that is volume mounted to interact with the 19.0.x engine.
```
Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by dgrove-oss** [comment]
Initial guess was wrong.   It is not a problem in docker version.  It is something related to how the container is being launched.   The openwhisk/invoker container contains the same 18.06 client as the standalone image and it is perfectly happy accessing the 19.03 engine on my Mac.  Looking to see what is different in how the two containers are configured.

**Comment by dgrove-oss** [comment]
🤦  -- nothing subtle.  a extra leading / in the volume mount which docker on linux seems to tolerate but docker on macOS does not.

**Comment by style95** [comment]
Awesome!
I am still curious why it worked on my iMac though.
