### ISSUE TITLE
Bind failed for TCP channel on endpoint

### ISSUE THREAD

**Issue by dmtrinh** [apache/openwhisk#5108]
## Environment details:

* local deployment, Ubuntu 20.04 on Windows Subsytem for Linux (WSL2), Windows 10 Pro version 20H2 (build 19042.928)
* Docker Desktop for Windows v3.3.1, Engine 20.10.5
* Visual Code with Remote - WSL plugin
* 
## Steps to reproduce the issue:

Follow Quickstart guide as described here:  https://github.com/apache/openwhisk#quick-start
The core:standalone:bootRun task throws java.net.BindException on port 3232 for playground

## Provide the actual results and outputs:

---------- 03:10:57 (dmtrinh@G15) :~/Dev/openwhisk ---------- 
==> ./gradlew core:standalone:bootRun
Build using Scala 2.12

> Configure project :core:scheduler
[task ':core:scheduler:assemble', task ':core:scheduler:assembleDist', task ':core:scheduler:build', task ':core:scheduler:buildDependents', task ':core:scheduler:buildEnvironment', task ':core:scheduler:buildNeeded', task ':core:scheduler:check', task ':core:scheduler:checkScalafmt', task ':core:scheduler:checkScalafmtAll', task ':core:scheduler:checkScoverage', task ':core:scheduler:checkScoverageScalafmt', task ':core:scheduler:checkTestScalafmt', task ':core:scheduler:classes', task ':core:scheduler:clean', task ':core:scheduler:cleanEclipse', task ':core:scheduler:cleanEclipseClasspath', task ':core:scheduler:cleanEclipseJdt', task ':core:scheduler:cleanEclipseProject', task ':core:scheduler:compileJava', task ':core:scheduler:compileScala', task ':core:scheduler:compileScoverageJava', task ':core:scheduler:compileScoverageScala', task ':core:scheduler:compileTestJava', task ':core:scheduler:compileTestScala', task ':core:scheduler:components', task ':core:scheduler:dependencies', task ':core:scheduler:dependencyInsight', task ':core:scheduler:dependentComponents', task ':core:scheduler:distTar', task ':core:scheduler:distZip', task ':core:scheduler:eclipse', task ':core:scheduler:eclipseClasspath', task ':core:scheduler:eclipseJdt', task ':core:scheduler:eclipseProject', task ':core:scheduler:help', task ':core:scheduler:install', task ':core:scheduler:installDist', task ':core:scheduler:jar', task ':core:scheduler:javadoc', task ':core:scheduler:model', task ':core:scheduler:prepareKotlinBuildScriptModel', task ':core:scheduler:processResources', task ':core:scheduler:processScoverageResources', task ':core:scheduler:processTestResources', task ':core:scheduler:projects', task ':core:scheduler:properties', task ':core:scheduler:reportScoverage', task ':core:scheduler:run', task ':core:scheduler:scaladoc', task ':core:scheduler:scalafmt', task ':core:scheduler:scalafmtAll', task ':core:scheduler:scoverageClasses', task ':core:scheduler:scoverageScalafmt', task ':core:scheduler:startScripts', task ':core:scheduler:tasks', task ':core:scheduler:test', task ':core:scheduler:testClasses', task ':core:scheduler:testScalafmt']
Scala sub-project 'gatling_tests' doesn't have Scoverage applied and will be ignored in parent project aggregation

> Task :core:standalone:bootRun

        ____      ___                   _    _ _     _     _
       /\   \    / _ \ _ __   ___ _ __ | |  | | |__ (_)___| | __
  /\  /__\   \  | | | | '_ \ / _ \ '_ \| |  | | '_ \| / __| |/ /
 /  \____ \  /  | |_| | |_) |  __/ | | | |/\| | | | | \__ \   <
 \   \  /  \/    \___/| .__/ \___|_| |_|__/\__|_| |_|_|___/_|\_\
  \___\/ tm           |_|
    
Git Commit: a201e02, Build Date: 2021-04-19T18:28:46-0500
================================================================================
Running pre flight checks ...

Local Host Name: 172.17.0.1
Local Internal Name: 172.17.0.1

[  OK   ] 'docker' cli found. (Docker version 20.10.6, build 370c289)
[  OK   ] 'docker' version 20.10.6 is newer than minimum supported 18.3.0
[  OK   ] 'docker' is running.
[  OK   ] 'wsk' cli found. (2021-04-01T23:49:54.523+0000)
[  OK   ] 'wsk' configured for namespace [guest].
[  OK   ] 'wsk' configured to connect to http://172.17.0.1:3233.
[  OK   ] Server port [3233] is free

================================================================================
[2021-04-26T03:11:04.974Z] [INFO] Starting OpenWhisk standalone on port 3233
[2021-04-26T03:11:05.253Z] [INFO] Slf4jLogger started
[2021-04-26T03:11:05.521Z] [INFO] Using [/home/dmtrinh/.openwhisk/standalone/server-3233] as data directory
[2021-04-26T03:11:05.774Z] [INFO] [#tid_sid_unknown] [StandaloneDockerClient] Detected docker client version 20.10.6
[2021-04-26T03:11:05.828Z] [INFO] [#tid_sid_standalone] [StandaloneDockerClient] running /usr/bin/docker ps --quiet --no-trunc --all --filter name=whisk- (timeout: 1 minute) [marker:invoker_docker.ps_start:6]
[2021-04-26T03:11:05.951Z] [INFO] [#tid_sid_standalone] [StandaloneDockerClient]  [marker:invoker_docker.ps_finish:128:31]
[2021-04-26T03:11:05.974Z] [INFO] [#tid_sid_standalone] [StandaloneDockerSupport] removing 0 containers launched for Standalone server support.
[2021-04-26T03:11:06.270Z] [WARN] Detected possible incompatible versions on the classpath. Please note that a given Akka HTTP version MUST be the same across all modules of Akka HTTP that you are using, e.g. if you use [10.1.11] all other modules that are released together MUST be of the same version. Make sure you're using a compatible set of libraries. Possibly conflicting versions [10.1.11, 10.1.10] in libraries [akka-http-spray-json:10.1.11, akka-parsing:10.1.11, akka-http2-support:10.1.10, akka-http-xml:10.1.11, akka-http:10.1.11, akka-http-core:10.1.11]
================================================================================
Launched service details

[ 3233  ] http://172.17.0.1:3233 (Controller)
[ 3232  ] http://172.17.0.1:3232/playground (Playground)

Local working directory - /home/dmtrinh/.openwhisk/standalone/server-3233
================================================================================
[2021-04-26T03:11:06.610Z] [ERROR] Bind failed for TCP channel on endpoint [/172.17.0.1:3232]
java.net.BindException: Cannot assign requested address
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:461)
        at sun.nio.ch.Net.bind(Net.java:453)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
        at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:59)
        at akka.io.TcpListener.<init>(TcpListener.scala:56)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at akka.util.Reflect$.instantiate(Reflect.scala:68)
        at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:101)
        at akka.actor.Props.newActor(Props.scala:212)
        at akka.actor.ActorCell.newActor(ActorCell.scala:648)
        at akka.actor.ActorCell.create(ActorCell.scala:674)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:547)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
        at akka.dispatch.Mailbox.run(Mailbox.scala:228)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[2021-04-26T03:11:06.765Z] [INFO] [#tid_sid_unknown] [MemoryArtifactStore] Created MemoryStore for [subjects]
[2021-04-26T03:11:06.788Z] [INFO] [#tid_sid_cli] [MemoryArtifactStore] [GET] 'subjects' finding document: 'id: guest' [marker:database_getDocument_start:93]
[2021-04-26T03:11:06.789Z] [INFO] [#tid_sid_cli] [MemoryArtifactStore]  [marker:database_getDocument_finish:94:1]
[2021-04-26T03:11:06.810Z] [INFO] [#tid_sid_cli] [MemoryArtifactStore] [PUT] 'subjects' saving document: 'id: guest, rev: null' [marker:database_saveDocument_start:115]
[2021-04-26T03:11:06.813Z] [INFO] [#tid_sid_cli] [MemoryArtifactStore]  [marker:database_saveDocument_finish:118:3]
[2021-04-26T03:11:06.814Z] [INFO] [#tid_sid_userBootstrap] [StandaloneOpenWhisk] Created user [guest]
[2021-04-26T03:11:06.848Z] [INFO] [#tid_sid_cli] [MemoryArtifactStore] [GET] 'subjects' finding document: 'id: whisk.system' [marker:database_getDocument_start:23]
[2021-04-26T03:11:06.849Z] [INFO] [#tid_sid_cli] [MemoryArtifactStore]  [marker:database_getDocument_finish:23:0]
[2021-04-26T03:11:06.853Z] [INFO] [#tid_sid_cli] [MemoryArtifactStore] [PUT] 'subjects' saving document: 'id: whisk.system, rev: null' [marker:database_saveDocument_start:27]
[2021-04-26T03:11:06.853Z] [INFO] [#tid_sid_cli] [MemoryArtifactStore]  [marker:database_saveDocument_finish:28:0]
[2021-04-26T03:11:06.853Z] [INFO] [#tid_sid_userBootstrap] [StandaloneOpenWhisk] Created user [whisk.system]
[2021-04-26T03:11:06.956Z] [WARN] Failed to attach the instrumentation because the Kamon Bundle is not present on the classpath
[2021-04-26T03:11:07.073Z] [INFO] [#tid_sid_unknown] [Config] system set value for limits.triggers.fires.perMinute
[2021-04-26T03:11:07.073Z] [INFO] [#tid_sid_unknown] [Config] system set value for limits.actions.sequence.maxLength
[2021-04-26T03:11:07.073Z] [INFO] [#tid_sid_unknown] [Config] system set value for limits.actions.invokes.concurrent
[2021-04-26T03:11:07.073Z] [INFO] [#tid_sid_unknown] [Config] system set value for whisk.api.host.name
[2021-04-26T03:11:07.073Z] [INFO] [#tid_sid_unknown] [Config] system set value for limits.actions.invokes.perMinute
[2021-04-26T03:11:07.074Z] [INFO] [#tid_sid_unknown] [Config] system set value for whisk.api.host.proto
[2021-04-26T03:11:07.074Z] [INFO] [#tid_sid_unknown] [Config] system set value for whisk.api.host.port
[2021-04-26T03:11:07.074Z] [INFO] [#tid_sid_unknown] [Config] system set value for runtimes.manifest
[2021-04-26T03:11:07.074Z] [INFO] [#tid_sid_unknown] [Config] system set value for port
[2021-04-26T03:11:07.122Z] [INFO] [#tid_sid_unknown] [LeanMessagingProvider] topic completedstandalone created
[2021-04-26T03:11:07.122Z] [INFO] [#tid_sid_unknown] [LeanMessagingProvider] topic health created
[2021-04-26T03:11:07.122Z] [INFO] [#tid_sid_unknown] [LeanMessagingProvider] topic cacheInvalidation created
[2021-04-26T03:11:07.122Z] [INFO] [#tid_sid_unknown] [LeanMessagingProvider] topic events created
[2021-04-26T03:11:07.180Z] [INFO] [#tid_sid_controller] [Controller] starting controller instance standalone [marker:controller_startup_counter:1423]
[2021-04-26T03:11:07.221Z] [INFO] [#tid_sid_unknown] [MemoryArtifactStore] Created MemoryStore for [whisks]
[2021-04-26T03:11:07.235Z] [INFO] [#tid_sid_dispatcher] [MessageFeed] handler capacity = 128, pipeline fill at = 128, pipeline depth = 256
[2021-04-26T03:11:07.256Z] [INFO] [#tid_sid_dispatcher] [MessageFeed] handler capacity = 128, pipeline fill at = 128, pipeline depth = 256
[2021-04-26T03:11:07.389Z] [INFO] [#tid_sid_unknown] [ExtendedDockerClient] Detected docker client version 20.10.6
[2021-04-26T03:11:07.390Z] [INFO] [#tid_sid_unknown] [InvokerReactive] LogStoreProvider: class org.apache.openwhisk.core.containerpool.docker.DockerCliLogStore
[2021-04-26T03:11:07.447Z] [INFO] [#tid_sid_unknown] [DockerClientWithFileAccess] Detected docker client version 20.10.6
[2021-04-26T03:11:07.595Z] [INFO] [#tid_sid_unknown] [StandaloneDockerContainerFactory] Standalone docker container factory config pullStandardImages: true
[2021-04-26T03:11:07.596Z] [INFO] [#tid_sid_invoker] [DockerClientWithFileAccess] running /usr/bin/docker ps --quiet --no-trunc --all --filter name=wsk0_ (timeout: 1 minute) [marker:invoker_docker.ps_start:1839]
[2021-04-26T03:11:07.630Z] [INFO] [#tid_sid_invoker] [DockerClientWithFileAccess]  [marker:invoker_docker.ps_finish:1873:34]
[2021-04-26T03:11:07.631Z] [INFO] [#tid_sid_invoker] [StandaloneDockerContainerFactory] removing 0 action containers.
[2021-04-26T03:11:07.752Z] [INFO] [#tid_sid_unknown] [MemoryArtifactStore] Created MemoryStore for [activations]
[2021-04-26T03:11:07.822Z] [INFO] [#tid_sid_invoker] [MemoryArtifactStore] [QUERY] 'subjects' searching 'namespaceThrottlings/blockedNamespaces [marker:database_queryView_start:2064]
[2021-04-26T03:11:07.828Z] [INFO] [#tid_sid_invoker] [MemoryArtifactStore]  [marker:database_queryView_finish:2071:6]
[2021-04-26T03:11:07.830Z] [INFO] [#tid_sid_unknown] [InvokerReactive] updated blacklist to 0 entries
[2021-04-26T03:11:07.869Z] [INFO] [#tid_sid_dispatcher] [MessageFeed] handler capacity = 8, pipeline fill at = 8, pipeline depth = 16
[2021-04-26T03:11:07.899Z] [INFO] [#tid_sid_controller] [Controller] loadbalancer initialized: LeanBalancer
[2021-04-26T03:11:07.902Z] [INFO] [#tid_sid_invokerWarmup] [ContainerPool] found 0 started and 0 starting; initing 2 pre-warms to desired count: 2 for kind:nodejs:10 mem:256 MB
[2021-04-26T03:11:07.926Z] [INFO] [#tid_sid_controller] [KindRestrictor] all kinds are allowed, the white-list is not specified
[2021-04-26T03:11:08.068Z] [INFO] [#tid_sid_unknown] [ExtendedDockerClient] Detected docker client version 20.10.6
[2021-04-26T03:11:08.096Z] [INFO] [#tid_sid_invokerWarmup] [DockerClientWithFileAccess] running /usr/bin/docker pull openwhisk/action-nodejs-v10:nightly (timeout: 10 minutes) [marker:invoker_docker.pull_start:2338]
[2021-04-26T03:11:08.097Z] [INFO] [#tid_sid_invokerWarmup] [DockerClientWithFileAccess] running /usr/bin/docker pull openwhisk/action-nodejs-v10:nightly (timeout: 10 minutes) [marker:invoker_docker.pull_start:2340]
[2021-04-26T03:11:08.432Z] [INFO] [#tid_sid_controller] [ActionsApi] actionSequenceLimit '50'
[2021-04-26T03:11:08.564Z] [ERROR] Bind failed for TCP channel on endpoint [/172.17.0.1:3233]
java.net.BindException: Cannot assign requested address
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:461)
        at sun.nio.ch.Net.bind(Net.java:453)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
        at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:59)
        at akka.io.TcpListener.<init>(TcpListener.scala:56)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at akka.util.Reflect$.instantiate(Reflect.scala:68)
        at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:101)
        at akka.actor.Props.newActor(Props.scala:212)
        at akka.actor.ActorCell.newActor(ActorCell.scala:648)
        at akka.actor.ActorCell.create(ActorCell.scala:674)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:547)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
        at akka.dispatch.Mailbox.run(Mailbox.scala:228)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Waiting for OpenWhisk server at http://172.17.0.1:3233 to start since 1.160 ms
[2021-04-26T03:11:09.201Z] [INFO] [#tid_sid_invokerWarmup] [DockerClientWithFileAccess]  [marker:invoker_docker.pull_finish:3444:1105]
[2021-04-26T03:11:09.405Z] [INFO] [#tid_sid_invokerWarmup] [DockerClientWithFileAccess]  [marker:invoker_docker.pull_finish:3648:1308]
[2021-04-26T03:11:09.406Z] [INFO] [#tid_sid_unknown] [StandaloneDockerContainerFactory] Pulled OpenWhisk provided image openwhisk/action-nodejs-v10:nightly
[2021-04-26T03:11:09.406Z] [INFO] [#tid_sid_unknown] [StandaloneDockerContainerFactory] Pulled OpenWhisk provided image openwhisk/action-nodejs-v10:nightly
[2021-04-26T03:11:09.439Z] [INFO] [#tid_sid_invokerWarmup] [DockerClientWithFileAccess] running /usr/bin/docker run -d --cpu-shares 256 --memory 256m --memory-swap 256m --network bridge -e __OW_API_HOST=http://172.17.0.1:3233 --name wsk0_1_prewarm_nodejs10 --pids-limit 1024 --cap-drop NET_RAW --cap-drop NET_ADMIN --ulimit nofile=1024:1024 --log-driver json-file openwhisk/action-nodejs-v10:nightly (timeout: 1 minute) [marker:invoker_docker.run_start:3681]
[2021-04-26T03:11:09.439Z] [INFO] [#tid_sid_invokerWarmup] [DockerClientWithFileAccess] running /usr/bin/docker run -d --cpu-shares 256 --memory 256m --memory-swap 256m --network bridge -e __OW_API_HOST=http://172.17.0.1:3233 --name wsk0_2_prewarm_nodejs10 --pids-limit 1024 --cap-drop NET_RAW --cap-drop NET_ADMIN --ulimit nofile=1024:1024 --log-driver json-file openwhisk/action-nodejs-v10:nightly (timeout: 1 minute) [marker:invoker_docker.run_start:3681]
[2021-04-26T03:11:09.850Z] [INFO] [#tid_sid_invokerWarmup] [DockerClientWithFileAccess]  [marker:invoker_docker.run_finish:4093:410]
[2021-04-26T03:11:09.858Z] [INFO] [#tid_sid_invokerWarmup] [DockerClientWithFileAccess] running /usr/bin/docker inspect --format {{.NetworkSettings.Networks.bridge.IPAddress}} 09d1e108c3819a6e77abd2d380eb26a878cea08d39369d8ea88bd142ac4bc161 (timeout: 1 minute) [marker:invoker_docker.inspect_start:4101]
[2021-04-26T03:11:09.889Z] [INFO] [#tid_sid_invokerWarmup] [DockerClientWithFileAccess]  [marker:invoker_docker.inspect_finish:4132:31]
[2021-04-26T03:11:09.941Z] [INFO] [#tid_sid_invokerWarmup] [DockerClientWithFileAccess]  [marker:invoker_docker.run_finish:4183:501]
[2021-04-26T03:11:09.942Z] [INFO] [#tid_sid_invokerWarmup] [DockerClientWithFileAccess] running /usr/bin/docker inspect --format {{.NetworkSettings.Networks.bridge.IPAddress}} b33a3c937bee774cae7b2dd32bb6b7b7a18bdfb382351d0f159963f675d9312f (timeout: 1 minute) [marker:invoker_docker.inspect_start:4185]
[2021-04-26T03:11:09.975Z] [INFO] [#tid_sid_invokerWarmup] [DockerClientWithFileAccess]  [marker:invoker_docker.inspect_finish:4217:32]
Waiting for OpenWhisk server at http://172.17.0.1:3233 to start since 2.197 min
[2021-04-26T03:13:22.117Z] [INFO] [#tid_sid_unknown] [ContainerPool] [kind: nodejs:10 memory: 256 MB] 2 expired prewarmed containers
[2021-04-26T03:13:22.117Z] [INFO] [#tid_sid_unknown] [ContainerPool] removing up to 100 of 2 expired containers
[2021-04-26T03:13:22.118Z] [INFO] [#tid_sid_unknown] [ContainerPool] removing expired prewarm of kind nodejs:10 with container ContainerId(09d1e108c3819a6e77abd2d380eb26a878cea08d39369d8ea88bd142ac4bc161) 
[2021-04-26T03:13:22.118Z] [INFO] [#tid_sid_unknown] [ContainerPool] removing expired prewarm of kind nodejs:10 with container ContainerId(b33a3c937bee774cae7b2dd32bb6b7b7a18bdfb382351d0f159963f675d9312f) 
[2021-04-26T03:13:22.119Z] [INFO] [#tid_sid_invokerWarmup] [ContainerPool] found 0 started and 0 starting; backfilling 1 pre-warms to desired count: 1 for kind:nodejs:10 mem:256 MB
[2021-04-26T03:13:22.120Z] [INFO] [#tid_sid_invokerNanny] [DockerClientWithFileAccess] running /usr/bin/docker rm -f 09d1e108c3819a6e77abd2d380eb26a878cea08d39369d8ea88bd142ac4bc161 (timeout: 1 minute) [marker:invoker_docker.rm_start:136363]
[2021-04-26T03:13:22.121Z] [INFO] [#tid_sid_invokerNanny] [DockerClientWithFileAccess] running /usr/bin/docker rm -f b33a3c937bee774cae7b2dd32bb6b7b7a18bdfb382351d0f159963f675d9312f (timeout: 1 minute) [marker:invoker_docker.rm_start:136363]
[2021-04-26T03:13:22.145Z] [INFO] [#tid_sid_invokerWarmup] [DockerClientWithFileAccess] running /usr/bin/docker run -d --cpu-shares 256 --memory 256m --memory-swap 256m --network bridge -e __OW_API_HOST=http://172.17.0.1:3233 --name wsk0_3_prewarm_nodejs10 --pids-limit 1024 --cap-drop NET_RAW --cap-drop NET_ADMIN --ulimit nofile=1024:1024 --log-driver json-file openwhisk/action-nodejs-v10:nightly (timeout: 1 minute) [marker:invoker_docker.run_start:136388]
[2021-04-26T03:13:22.513Z] [INFO] [#tid_sid_invokerNanny] [DockerClientWithFileAccess]  [marker:invoker_docker.rm_finish:136756:393]
[2021-04-26T03:13:22.641Z] [INFO] [#tid_sid_invokerNanny] [DockerClientWithFileAccess]  [marker:invoker_docker.rm_finish:136883:520]
[2021-04-26T03:13:22.720Z] [INFO] [#tid_sid_invokerWarmup] [DockerClientWithFileAccess]  [marker:invoker_docker.run_finish:136962:574]
[2021-04-26T03:13:22.720Z] [INFO] [#tid_sid_invokerWarmup] [DockerClientWithFileAccess] running /usr/bin/docker inspect --format {{.NetworkSettings.Networks.bridge.IPAddress}} ce9d8fb7812b2ed691674a719ec56bb5f6af02ae1dbf14ed8015097d99bb9d8e (timeout: 1 minute) [marker:invoker_docker.inspect_start:136963]
[2021-04-26T03:13:22.749Z] [INFO] [#tid_sid_invokerWarmup] [DockerClientWithFileAccess]  [marker:invoker_docker.inspect_finish:136992:29]
<============-> 97% EXECUTING [2m 31s]
> :core:standalone:bootRun

**Comment by eliashussary** [comment]
I am facing the same issue.

```sh
[2021-04-29T14:01:16.591Z] [ERROR] Bind failed for TCP channel on endpoint [/172.17.0.1:3233]
java.net.BindException: Cannot assign requested address
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:455)
        at java.base/sun.nio.ch.Net.bind(Net.java:447)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
        at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:59)
        at akka.io.TcpListener.<init>(TcpListener.scala:56)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at akka.util.Reflect$.instantiate(Reflect.scala:68)
        at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:101)
        at akka.actor.Props.newActor(Props.scala:212)
        at akka.actor.ActorCell.newActor(ActorCell.scala:648)
        at akka.actor.ActorCell.create(ActorCell.scala:674)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:547)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:569)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
        at akka.dispatch.Mailbox.run(Mailbox.scala:228)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Waiting for OpenWhisk server at http://172.17.0.1:3233 to start since 3.522 ms
```

**Comment by shazron** [comment]
@chetanmeh do you have any hints on what's going on? I tried this on non-wsl2 Ubuntu environment and got the same thing. This was working a couple of months ago, and the .jar built hasn't changed for me, so it might be something with the java environment.

**Comment by frankfurtmacmoses** [comment]
Can you please help. I can't seem to be able to resolve this issue in four days. I am getting the same error as above

**Comment by rabbah** [comment]
@frankfurtmacmoses sorry you're having trouble. Are you also on WSL?

I can't reproduce on Mac or Linux. Are you able to run any docker commands as a sanity check?

**Comment by Asrst** [comment]
Hi @rabbah , this might be happening due to firewall or limited privileges. I am struck with the same issue, while trying to setup openwhisk on gitpod (linux), with limited sudo & docker access.

Here you can access code workspace using this link, https://gitpod.io/#snapshot/7ed2e336-8cba-4a49-8271-057625ae6ea3
(cloned openwhisk repo - tag 1.0.0)

**Comment by shazron** [comment]
Long thread here: https://github.com/docker/for-win/issues/3171

Even though it's an issue created in 2019, people are still having the issue.

There may be several workarounds:
1. https://github.com/docker/for-win/issues/3171#issuecomment-459205576
2. https://github.com/docker/for-win/issues/3171#issuecomment-570688374
3. https://github.com/docker/for-win/issues/3171#issuecomment-572571882
4. https://github.com/docker/for-win/issues/3171#issuecomment-788808021

I tried no. 4, it didn't work. Didn't have a chance to try the others yet.

**Comment by GitHubDiom** [comment]
Facing the same issue in Apple silicon.

**Comment by moritzraho** [comment]
A workaround for starting the standalone stack in wsl2 is to run the controller in a container: https://github.com/apache/openwhisk/tree/master/core/standalone#launching-openwhisk-standalone-with-docker. This worked for me.

**Comment by moritzraho** [comment]
Another one for running the jar directly in WSL2:
- install docker-ce inside WSL2: https://docs.docker.com/engine/install/ubuntu/
- then `sudo service docker start`
- Finally you will need the standalone controller to bind to localhost by adding the following options.
``` 
java \
-Dwhisk.standalone.host.name=localhost \
-Dwhisk.standalone.host.internal=127.0.0.1 \
-Dwhisk.standalone.host.external=localhost \
-jar openwhisk-standalone.jar
```
- From Windows browser access http://localhost:3232  for the playground UI or http://localhost:3233 for the controller

**Comment by jadeye** [comment]
Same issue...

**Comment by Shanmukh1609** [comment]
I have been trying to deploy the open whisk through 
![image](https://github.com/user-attachments/assets/79821383-b6db-4acb-9574-61562c24f0c5)
on windows 11 WSL 2 -Ubuntu 20.04.6 LTS , It is not ending, I have left it.
![image](https://github.com/user-attachments/assets/2ec65fbc-0afc-4f4d-b791-ad234e17f51e). 
I have encountered the error upon **./gradlew core:standalone:bootRun --info**
![image](https://github.com/user-attachments/assets/2cc98cb3-0db4-4a01-8257-ffed11d85337)

I have used the method specified by @moritzraho, I was able to see the function playground. So is it possible to upload the zip files through this, I am guessing this may not happen , If possible let me know. But TCP problem has not been solved
