### ISSUE TITLE
NoSuchMethodError on ActivationServiceClient

### ISSUE THREAD

**Issue by style95** [apache/openwhisk#5317]
I am unsure where this regression comes from but the invoker complains about the `NoSuchMethodError`.

## Steps to reproduce the issue:

1.  Just deploy OpenWhisk.
2.  Invoker complains about it when it tries to warm up.

## Provide the actual results and outputs:

```
[2022-08-26T07:52:50.738Z] [INFO] [#tid_sid_invokerHealthManager] [WhiskAction] write initiated on new cache entry
Exception in thread "pool-1-thread-3" java.lang.NoSuchMethodError: io.grpc.internal.AbstractManagedChannelImplBuilder.<init>(Ljava/lang/String;)V
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:137)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.forTarget(NettyChannelBuilder.java:127)
        at akka.grpc.internal.NettyClientUtils$.createChannel(NettyClientUtils.scala:41)
        at akka.grpc.internal.ClientState.<init>(ClientState.scala:30)
        at org.apache.openwhisk.grpc.DefaultActivationServiceClient.<init>(ActivationServiceClient.scala:37)
        at org.apache.openwhisk.grpc.ActivationServiceClient$.apply(ActivationServiceClient.scala:29)
        at org.apache.openwhisk.core.invoker.FPCInvokerReactive.warmUpScheduler(FPCInvokerReactive.scala:412)
        at org.apache.openwhisk.core.invoker.FPCInvokerReactive.$anonfun$warmUp$10(FPCInvokerReactive.scala:457)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at org.apache.openwhisk.core.invoker.FPCInvokerReactive.$anonfun$warmUp$8(FPCInvokerReactive.scala:456)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:897)
        at org.apache.openwhisk.core.invoker.FPCInvokerReactive.$anonfun$warmUp$7(FPCInvokerReactive.scala:452)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:285)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at org.apache.openwhisk.core.invoker.FPCInvokerReactive.$anonfun$warmUp$6(FPCInvokerReactive.scala:449)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by bdoyle0182** [comment]
Is there any timeline on when this was maybe introduced? Could it have been there awhile or something you know was introduced in the last week or two?

**Comment by bdoyle0182** [comment]
Reproduced on my end. Can't run any functions successfully.

**Comment by bdoyle0182** [comment]
Can verify was introduced on or after this commit I believe. https://github.com/apache/openwhisk/commit/7de8bad25fbad49b2613c70b12a3abe9b24c857e

Didn't have an issue on the commit before it until I bumped to latest
