### ISSUE TITLE
Invoker crashed due to lack of ZookeeperHost Config

### ISSUE THREAD

**Issue by FangyueLiu123** [apache/openwhisk#5399]
## Environment details:

* local deployment, native ubuntu, Mac OS, Kubernetes, ...
* version of docker, ubuntu, ...

## Steps to reproduce the issue:

1.   Deploy the whole stack on k8s, including zookeeper, redis, couchdb and so on.

## Provide the expected results and outputs:

```

invoker should work normally.

```

## Provide the actual results and outputs:

```

Invoker crashed:
Exception in thread "main" java.lang.IllegalArgumentException: connectionString cannot be null or empty
        at org.apache.curator.shaded.com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
        at org.apache.curator.ensemble.fixed.FixedEnsembleProvider.<init>(FixedEnsembleProvider.java:55)
        at org.apache.curator.ensemble.fixed.FixedEnsembleProvider.<init>(FixedEnsembleProvider.java:43)
        at org.apache.curator.framework.CuratorFrameworkFactory$Builder.connectString(CuratorFrameworkFactory.java:234)
        at org.apache.curator.framework.CuratorFrameworkFactory.newClient(CuratorFrameworkFactory.java:109)
        at org.apache.curator.framework.CuratorFrameworkFactory.newClient(CuratorFrameworkFactory.java:94)
        at org.apache.openwhisk.core.invoker.InstanceIdAssigner.setAndGetId(InstanceIdAssigner.scala:37)
        at org.apache.openwhisk.core.invoker.Invoker$.main(Invoker.scala:191)
        at org.apache.openwhisk.core.invoker.Invoker.main(Invoker.scala)

```

## Additional information you deem important:

* changes you did or observed in the environment

It seems that invoker crash because `config.ZookeeperHosts` is null string.
This may be caused by #5375 which remove it from invoker, however, CuratorFrameworkFactory.newClient requires it to be not null when zookeeper is used.

Adding ZookeeperHosts to the requiredProperties solves this bug.

**Comment by style95** [comment]
I met this problem today.

**Comment by FangyueLiu123** [comment]
Thanks you a lot for solving this.
